### ISSUE TITLE
Uncaught Error: History.js Adapter has already been loaded...

### ISSUE THREAD

**Issue by mandrasch** [browserstate/history.js#189]
Hey Devs!

Very nice plugin/library! Is there a way to get rid of the "Uncaught Error: History.js Adapter has already been loaded... ". I tried with try/catch, but that doesn't work.

I'm using http://labjs.com/ and unfortunately I can't control/check right now if a script was loaded before, so double loading can happen and then historyjs breaks the application with this uncaught error.

Thanks in advance,
Matthias

**Comment by WiechersV** [comment]
+1

**Comment by incorvia** [comment]
seems to happen to me too

**Comment by hatemalimam** [comment]
I can't see why this issue is closed !

**Comment by akievet** [comment]
+1

**Comment by designjockey** [comment]
+1

**Comment by shiham55** [comment]
+1

**Comment by jclay** [comment]
Unfortunately you're not able to catch this error since it's being thrown within the anonymous function that it's defined within. 

Here's a workaround - simply unload History.js prior to loading it to ensure that it is able to setup. This has some side effects if you're planning on storing History between page reloads.

```html
<script type="text/javascript">
    delete History
</script>

<script src="http://www.yourwebsite.com/history.js/scripts/bundled/html4+html5/jquery.history.js"></script>

```

**Comment by itbra** [comment]
+1

**Comment by O-Zone** [comment]
+1

I'm gonna go with jclays proposed unload workaround, but it feels a bit stupid to unload everything when it obviously is a bug that should be fixed in this package instead. It is a 4 years old bug now? :-O
