### ISSUE TITLE
Expose current state index

### ISSUE THREAD

**Issue by baseten** [browserstate/history.js#235]
Hi, it might be useful to expose a method for getting the current state's index in the stack and perhaps methods for duplicating states? For example supposing I want a button that takes the user back to the previous state but without popping the current state off the stack.

Currently I'm doing this:

``` javascript
if(History.savedStates.length > 1) {
    var lastState = History.getStateByIndex(History.savedStates.length - 2);
    History.pushState(lastState.data, lastState.title, lastState.url);
}
```

But I probably shouldn't be messing with the savedStates stack directly...

**Comment by monteduro** [comment]
if the user go back and forward the currentIndex keep growing. Not god.
