### ISSUE TITLE
PageJS single page app refresh

### ISSUE THREAD

**Issue by sagar-ganatra** [browserstate/history.js#392]
I'm working on a Backbone application and instead of using the Backbone Router, I'm looking at PageJS. However, I have run into a caveat. The application works fine when the user browses through it and the URL is updated, but on clicking refresh the route is not identified. To overcome this, I will have to resort to hash based URLs. For example, <domain_name>/#orders. This is not getting picked up in PageJS. Is there any workaround to this?

**Comment by paulocoghi** [comment]
@sagar-ganatra , plese close this issue.
