### ISSUE TITLE
IE and iframe problem

### ISSUE THREAD

**Issue by desaintflorent** [browserstate/history.js#43]
When using history.js in an iframe with IE8-9 ( i didn't test with older browser but the same issue is expected ), If we hit the back button, IE go back one state but the change event is not fired.

History.js v1.7 - Windows Vista - IE8 - IE9

**Comment by iadc2005** [comment]
right, I am also going through this issue. And it really depressed me for it is OK with Chrome and Firefox? Can anyone give some little help???
