### ISSUE TITLE
History.js is not compatible with Webpack's require()

### ISSUE THREAD

**Issue by FractalizeR** [browserstate/history.js#433]
DELETED

**Comment by megatolya** [comment]
@FractalizeR Did you solve this problem?

**Comment by FractalizeRMoby** [comment]
I don't actually remember ;) I guess so.

**Comment by mjancewicz** [comment]
@megatolya You can do it with imports-loader:

`require('imports!history.js/history.js');
require('imports!history.js/history.adapter.ender.js');`
