### ISSUE TITLE
AMD version of history.js?

### ISSUE THREAD

**Issue by ashandrien** [browserstate/history.js#452]
Hi, I searched a bit and was unable to find an issue related to this.  I was going to try to wrap history.js in a define() call, but I was wondering if there is already an AMD/requirejs compatible version of history.js?

**Comment by jagandecapri** [comment]
Did you find any?

**Comment by ashandrien** [comment]
I went with a routing library - director.JS

**Comment by jagandecapri** [comment]
@ashandrien Alright, cool. :+1:
