### ISSUE TITLE
Defining a base href does not work as described

### ISSUE THREAD

**Issue by JohannesKlauss** [browserstate/history.js#467]
According to this doc https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#examples setting a baseName involves createHistory from the history module.

Using history@4.2.0 and react-router@2.8.1 JavaScript throws an error stating, that createHistory is not a function.

How can i define a base href, so that my React application can live in a subdirectory?

**Comment by dherran** [comment]
Wrong repository. Closing.
