### ISSUE TITLE
security scan result

### ISSUE THREAD

**Issue by supreme-core** [browserstate/history.js#493]
Hi,

The current state of history.js is triggering alerts from security scan. Some of the dependencies are outdated and no longer valid under security scan.

Please recommend an open-source alternative that can work as a replacement.

**Comment by sushmak02** [comment]
Facing the same issue, any solution for this or any alternate availble? Please suggest

**Comment by supreme-core** [comment]
I have removed the dependencies of history.js without having adverse effect on calls to history.js
