### ISSUE TITLE
detect Back-navigation in onstatechange event callback

### ISSUE THREAD

**Issue by jokeyrhyme** [browserstate/history.js#70]
Forgive me if this has been covered elsewhere (although I did do a quick check first).

I have a jQuery web application using History.JS, and I have all my user actions triggering calls to "pushState()" or "replaceState()". Then I have an event hook like:

``` javascript
$(window).bind('statechange', function(event) {
    var state = History.getState();
    History.log('History.stateChange: ' + $.param(state.data) + ' ' + state.url, event);
    // check state object here and control the display of articles or UI elements
    // eg if state.data.page === 1 then hide all pages except for page 1
    event.preventDefault();
    return false;
});
```

This is working wonderfully. However, I would like to be able to detect whether the Back button was pressed. Specifically, this is so I can use a reverse-animation to emphasis that we are going backwards to a previous page.

Is there a way to identify the difference between a pushState() and a back() once we are in the onstatechange event callback? 

I took a look at the History global object, and there are 2 arrays "storedStates" and "savedStates". In testing, however, these always seem to increase in size, no matter the navigation direction, so I cannot simply test the Array.length to see if it shrinks on Back (as I first hoped).

My web application originally had a crudely implemented "back stack" that basically worked like breadcrumbs: increasing in size for each forward navigation, and shrinking in size whenever we went Back and popped the last visited page. Is there any benefit in History.JS adopting similar behaviour?

Alternatively, perhaps a property of the State object can indicate Back-navigation? If we can cull all duplicate states, perhaps the position of the current state in either of the previously mentioned arrays can be used to test for this?

**Comment by hosein71** [comment]
So, there isn't any way to detect back button is pressed or forward button?
