### ISSUE TITLE
History.js and its plugins crash when combined into a single JavaScript file.

### ISSUE THREAD

**Issue by garyv** [browserstate/history.js#83]
On websites that combine multiple JavaScript files into one, history.js crashes with "undefined method" errors.

I consider this a bug because:
- Their should (theoretically) be no difference between running the same javascript code as one file or a series of separate files, as each line of code is executed sequentially.
- Combining multiple files of the same type to reduce the number of HTTP requests is a common and widely accepted practice in web optimization. (ref: http://developer.yahoo.com/performance/rules.html)

Details:
- It can be reproduced on any site using history.js and its plugins by replacing the separate script tags with a single script tag referencing a file with the code from history.js and its plugins combined.
- I've reproduced it in Firefox 5, Safari 5, and Chrome, so believe the bug is browser independent

Quick and dirty fix:

Add a millisecond delay to each script file after the first one.

```
// contents of history.adapter.jquery.js
setTimeout(function(){
    // contents of history.js
}, 1);
setTimeout(function(){
    // contents of history.html4.js
}, 1);
```

This is clearly too hacky to be a permanent fix, but it illustrates the problem well: 
History.js is dependent on the delay normally caused by loading each script with a separate HTTP request.

**Comment by Angelinsky7** [comment]
Still not working in 2017...
